### PR TITLE
Updated comt_projects.json page and new image in images/comt

### PR DESCRIPTION
**Pull request by torieketcham**
I added new projects to the comt_projects.json file and also added an image to the images/comt folder.

### CODE REVIEW

**Review by gitchrisadams — CHANGES_REQUESTED** [review]
@torieketcham Can you make it so only relevant files are committed and not .DS_Store and package-lock.json  If you git add specific file name versus git add dot to add all, you can just add individual files.

**Comment by torieketcham** [comment]
Okay, will do. DO I need to create a new request?

**Comment by gitchrisadams** [comment]
You can push up to this current PR or you can create a new branch and create a new PR. Whatever you find easier.

**Comment by torieketcham** [comment]
I created a new branch, added the two files and committed, but I get a message that says that the master is already up to date when I merge. I'm not sure how to specify only those two changed files in the PR.

**Comment by gitchrisadams** [comment]
Closing this PR in favor of this: https://github.com/ioos/comt-landing/pull/18

**Pull request closed without merging**
