### PR TITLE
PDF addition

### PR DESCRIPTION
**Pull request by torieketcham**
small text changes and link to the PDF - a screenshot of the link in the code is attached.
Screen Shot 2019-04-05 at 1 35 34 PM

### CODE REVIEW

**Comment by gitchrisadams** [comment]
@torieketcham Can you confirm you are able to view the pdf when you have the app running locally and clicking on the link?, I get error: "Cannot read property 'variablesColored' of undefined". Also not able to download the pdf by right clicking and save as. Sorry it took me awhile to review this one, I though I had already looked at it.

**Comment by torieketcham** [comment]
I apologize, Chris - I had checked it locally, but somehow managed to commit the version of the project file that was missing a / in the link. I've tested this and it should work - could you let me know if it looks okay to you now?

**Comment by gitchrisadams** [comment]
@torieketcham This is all set and deployed.

**Comment by torieketcham** [comment]
Thank you!

**Pull request merged**
