### PR TITLE
updated json project file with new content/shortened titles; added image to images/comt

### PR DESCRIPTION
**Pull request by torieketcham**
Left-hand nav scrolls properly on subpages and does not get cut off at 768px height.

### CODE REVIEW

**Comment by gitchrisadams** [comment]
My laptop is probably a good test because it is at 1300x768. With the top chrome tabs and normal bottom menubar at 600px it gets cut off:
image

@Bobfrat Thoughts on this?

**Comment by gitchrisadams** [comment]
Also need to check in the image file:
image

**Comment by torieketcham** [comment]
Sorry - do you mean the image didn't get committed?

**Comment by gitchrisadams** [comment]
Yes.

**Comment by torieketcham** [comment]
Sorry about that. Should be up there now.

**Comment by torieketcham** [comment]
Hello - just wondering what you all have decided re: merging these commits?

**Pull request merged**
