### PR TITLE
Text updates

### PR DESCRIPTION
**Pull request by torieketcham**
Made small text changes to the project page.

### CODE REVIEW

**Comment by torieketcham** [comment]
Would it be possible to merge this today please?

**Comment by gitchrisadams** [comment]
Looking at this now.

**Review by gitchrisadams — APPROVED** [review]

**Comment by gitchrisadams** [comment]
@torieketcham this is all set and deployed. To confirm you can see this page: https://comt.ioos.us/projects/data_framework no longer has the "Other Investigators" section.

cc: @Bobfrat

**Comment by torieketcham** [comment]
Thank you very much!!

**Pull request merged**
